### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Alexei412** [Coding-Enthusiast/FinderOuter#58]
The software works great. There are no problems, I tested it many times.There was a problem. There is a private key that lacks the last 9 characters. At the same time, in some places the op is poorly readable. According to the contour, you can roughly determine what was there. Accordingly, is it possible to modify so that in certain places, it was possible to put a range of characters. Example below.

✅✅(o/b/p/d/g)✅✅✅✅(7/Z/T)✅✅✅✅✅✅✅(Z/2)✅✅✅✅✅✅✅(n/p/o/g/q)✅✅✅✅✅✅✅✅✅✅(r/t/f)✅✅✅✅✅✅✅?????????

✅ - famous
(.../.../...) - probable
? - unknown

**Comment by Coding-Enthusiast** [comment]
The latest release (v. 0.15.0.0) introduced a new option called `Search Space`. After filling all the boxes expand Advanced option and click `Start` button. Now you can move through the missing positions one at a time and enter a limited number of possibilities. Like this:  
![SearchSpace](https://user-images.githubusercontent.com/20510382/171025423-4f6feb64-bfee-4820-99bd-7fb423ef1491.jpg)

You can enter a character in the textbox on the left and click one of the buttons below to add the exact character or other characters similar to it. For example enter `g` and click `Exact letter` to add `g` to the list.  
There are other buttons on the right to ease this process like `Add all letter` to add all base58 characters.  
You can always modify the list by selecting one item and clicking `Remove selected`.  

When you are done setting all 9 positions click `Find`.

**Comment by Alexei412** [comment]
If you specify 20 unknown characters (WIF1), then the program starts and runs. 
WIF1-✅✅✅✅✅✅✅✅✅✅✅??????????✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅??????????
*****
If you specify 10 unknown characters and 2-3 with the specified options (WIF2), everything works the same way.
WIF2-✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅(n/p/o/g/q)✅✅✅✅✅✅✅✅✅✅(r/t/f)✅✅✅✅✅✅✅?????????
*****
If you specify 10 unknown characters and 8-10 with the specified options (WIF3), then the program simply closes.
WIF3-✅✅(o/b/p/d/g)✅✅✅✅(7/Z/T)✅✅✅(r/t/f)✅✅✅(Z/2)✅✅✅✅✅✅✅(n/p/o/g/q)✅✅(r/t/f)✅(r/t/f)✅✅✅✅✅(r/t/f)✅✅✅✅✅✅✅?????????

**Comment by Coding-Enthusiast** [comment]
@jaaawsh  
I fixed some of the SearchSpace related bugs in the latest release ([v0.16.0](https://github.com/Coding-Enthusiast/FinderOuter/releases/tag/v0.16.0.0)), use that if you aren't already.  
In any case this needs more investigation since what you described is an uncaught and unexpected exception which I also couldn't reproduce. I'm currently increasing the overall test coverage and hopefully this will be caught there.

**Comment by jaaawsh** [comment]
@Coding-Enthusiast 

I am using the latest release, I'm using the newest, already compiled release. 

The version of windows I am using is 
Edition	Windows 10 Home
Version	21H2
Installed on	‎4/‎23/‎2021
OS build	19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

and it is a 64-bit operating system, x64-based processor


It doesn't seem to have a problem when it's just a few missing characters that I am searching for, but the search goes so extremely quick anyway when you're only missing a few characters that it's non-consequential to cut the search time down from 2 minutes to a few seconds.  However when you're looking for 7 missing characters searching the entire search space vs. a narrowed down search space the difference in size can be tens of billions of keys to search through.

interesting that you haven't been able to reproduce the bug.

**Comment by Coding-Enthusiast** [comment]
@jaaawsh checkout the latest release to see if the bug is fixed.

**Comment by jeremysboyle** [comment]
I still experienced the same thing as the program crashes when I input data for a particular line but works fine if it didn't search the line and there is line 8 from end that gives me new set of search characters instead of the ones I originally entered in the search box. I input RSVW and the software search EFGH instead
